from __future__ import annotations

FAILED_CLOSED = "FAILED_CLOSED"

RECEIVED = "RECEIVED"
PUBLICATION_GOVERNANCE_EVIDENCE_VALIDATED = "PUBLICATION_GOVERNANCE_EVIDENCE_VALIDATED"
PUBLICATION_POLICY_VALIDATED = "PUBLICATION_POLICY_VALIDATED"
PUBLICATION_INTENT_PREPARED = "PUBLICATION_INTENT_PREPARED"
READY_FOR_PUBLICATION_EXECUTION_GOVERNANCE_PLAN_ONLY = "READY_FOR_PUBLICATION_EXECUTION_GOVERNANCE_PLAN_ONLY"

ALLOWED_TRANSITIONS = {
    (RECEIVED, PUBLICATION_GOVERNANCE_EVIDENCE_VALIDATED),
    (PUBLICATION_GOVERNANCE_EVIDENCE_VALIDATED, PUBLICATION_POLICY_VALIDATED),
    (PUBLICATION_POLICY_VALIDATED, PUBLICATION_INTENT_PREPARED),
    (PUBLICATION_INTENT_PREPARED, READY_FOR_PUBLICATION_EXECUTION_GOVERNANCE_PLAN_ONLY),
}

FORBIDDEN_STATES = {
    "PUBLISHED",
    "POSTED",
    "SCHEDULED_FOR_PUBLICATION",
    "PUBLICATION_CHANNEL_UPDATED",
    "N8N_TRIGGERED",
    "WEBHOOK_TRIGGERED",
    "CAPA9_TRIGGERED",
    "QUEUE_WRITTEN",
    "QUEUE_ITEM_CREATED",
    "QUEUE_ITEM_UPDATED",
    "CONTENT_GENERATED",
    "FINALIZED",
    "ARGOS_BRIDGE_BUILT",
}


def validate_transition(from_state: str, to_state: str) -> tuple[bool, str | None]:
    if to_state in FORBIDDEN_STATES:
        return False, "FORBIDDEN_PUBLICATION_GOVERNANCE_STATE"
    if (from_state, to_state) not in ALLOWED_TRANSITIONS:
        return False, "ILLEGAL_PUBLICATION_GOVERNANCE_TRANSITION"
    return True, None


def is_forbidden_state(state: str) -> bool:
    return state in FORBIDDEN_STATES


def validate_plan_only_path() -> tuple[bool, tuple[str, ...]]:
    path = [
        RECEIVED,
        PUBLICATION_GOVERNANCE_EVIDENCE_VALIDATED,
        PUBLICATION_POLICY_VALIDATED,
        PUBLICATION_INTENT_PREPARED,
        READY_FOR_PUBLICATION_EXECUTION_GOVERNANCE_PLAN_ONLY,
    ]
    errors: list[str] = []
    for current, nxt in zip(path, path[1:]):
        ok, error = validate_transition(current, nxt)
        if not ok and error:
            errors.append(error)
    return not errors, tuple(errors)
